### ISSUE TITLE
Update existing packaged deck and retaining the progress

### ISSUE THREAD

**Issue by lamyergeier** [julien-sobczak/anki-cli#1]
As mentioned in Readme. We can import the packaged Anki deck generated by anki-cli. Can we also, copy and paste _existing anki packaged deck_ to the sandbox folder, such that it can be updated? Is it possible to preserve the progress of the deck, if we update the deck?

**Comment by julien-sobczak** [comment]
I'm not sure to understand what you are really trying to do.

The current code only creates new cards from an input file and does not support updating existing cards in batch. Using the flag `--anki-dir`, you can directly add these new cards to your current Anki collection but make sure to backup the whole Anki directory first. 

Personally, I prefer to generate a new `apkg` file and then move the cards to my existing deck. I included a short video in the blogpost at the end https://www.juliensobczak.com/write/2020/12/26/anki-scripting-for-non-programmers.html to demonstrate this approach.

If what you want to do is update existing cards/notes, a custom Python script (similar to the code present in this project) is probably the simpler solution.

**Comment by lamyergeier** [comment]
Thanks! I have seen your videos. 

> You said:  Using the flag --anki-dir, you can directly add these new cards to your current Anki collection but make sure to backup the whole Anki directory first.

But, I wanted to know if this (using anki-cli to add to existing deck) preserves the progress of study of my deck? For example, does it preserve the data like which existing words in the deck are due for review.

**Comment by julien-sobczak** [comment]
To be honest, I haven't tried to run the program on my own Anki decks directly. The code of this project relies heavily on the Anki Python module, which I don't contribute, and therefore there is always some risks.     

The code of the CLI, however, is very similar to what you would do if you create new notes in Anki Desktop. The scheduling information about existing cards must not be affected when adding new ones with this program.
