### ISSUE TITLE
Article may be out of date "Anki Scripting for Non-Programmers"

### ISSUE THREAD

**Issue by dangbert** [julien-sobczak/anki-cli#2]
Hi Julien, wasn't sure how else to contact you (or comment on your article) but I wanted to share a problem I ran into when following your "Anki Scripting for Non-Programmers" article, and hopefully this will help anyone else in the future that runs into it.  You article was super helpful and I just created my first Anki cards programmatically btw so thank you for writing up such a good guide!

The one problem I ran into was that no matter what I did, the cards I was creating were being added to the wrong deck. Looking through the source code for Anki's API it appears that the [`Collection:addNote()`](https://github.com/ankitects/anki/blob/2.1.44/pylib/anki/collection.py#L382) function is now marked as `legacy`, and the problem is that this function uses the deck ID from the note's model rather than the currently selected deck ID [see here](https://github.com/ankitects/anki/blob/2.1.44/pylib/anki/collection.py#L382).  My fix was to use [`Collection:add_note()`]() instead: `col.add_note(note, deck['id'])`.

[Here's the full script I made for reference](https://github.com/dangbert/clippy-kindle/blob/45b395511274f2ce42cc9df1205c6ed871973399/ankiImport.py#L73) which correctly adds to the desired deck now.

Note I was using version `2.1.44` of the Anki pip package, on Ubuntu 20.

**Comment by julien-sobczak** [comment]
Hi Daniel,

Thanks for reporting the issue as clearly as you did. I fixed the code in the blog post too. 

Have fun reviewing your flashcards ;)
