### ISSUE TITLE
Installer anki-cli nécessite de résoudre le cirque des versions aqt/anki

### ISSUE THREAD

**Issue by sosie-js** [julien-sobczak/anki-cli#4]
Bonjour Julien,

J'ai fini par tomber sur toi en recherchant le schema de Anki, puis le scripting qui est impressionant que [j'ai recupere sur webarchive](http://web.archive.org/web/20171206081618/https://www.juliensobczak.com/tell/2016/12/26/anki-scripting.html) qui est [une version déconnectée de celle que tu as mise sur ton site](https://www.juliensobczak.com/write/2016/12/26/anki-scripting.html).

Je dois dire que Anki est nebuleux point de vue version et doc et que je galere
depuis un moment à essayer de savoir comment on cree des notes et cards et surtout efface les decks
 etc. j'en suis arrivé en fait à faire aussi un client (que je n'ai pas encore posté car j'arrive pas à valider les tests de anki-connect tournant en rond). j'ai vite testé ton client mais j'ai rencontré le bins d'incompatibilité dont tu as fait part. Voici ce qui mest arrivé et comment j'ai résolu ce bins.

```
Sur debian 10 (*), le client anki est obsolète  2.1.8 avec sudo apt-get install anki
si on utilise `sudo pip3 install anki`, on est propulsé à la version 2.1.47
et  ton client demande impérativement la version 2.1.44
```

j'en suis arrivé très vite à ce jeu à embrouiller mon systeme avec aqt 2.1.47/anki 2.4.44 et à ne plus reussir à lancer anki ayant l'erreur:
```python
Traceback (most recent call last):
  File "/usr/local/bin/anki", line 5, in <module>
    from aqt import run
  File "/usr/local/lib/python3.9/site-packages/aqt/__init__.py", line 21, in <module>
    from aqt import gui_hooks
  File "/usr/local/lib/python3.9/site-packages/aqt/gui_hooks.py", line 11, in <module>
    from aqt.hooks_gen import *
  File "/usr/local/lib/python3.9/site-packages/aqt/hooks_gen.py", line 14, in <module>
    from anki.decks import DeckDict, DeckConfigDict
ImportError: cannot import name 'DeckDict' from 'anki.decks' (/usr/local/lib/python3.9/site-packages/anki/decks.py)

```

Alors je suggere dans ta doc **non pas d'installer anki** mais la meme version aqt qui lui installera anki
c'est à dire qu'il faut oublier apt-get install python3 -m pip install et aller à l'essentiel
a) on vire les versions dejà installées
```
sudo apt-get remove anki
sudo pip3 uninstall anki
sudo pip3 uninstall aqt
```
b) puis on prépare le terrain pour rendre ton client happy
```
sudo pip3 install aqt==2.1.44
sudo pip3 install anki-cli-unofficial
```

=> Successfully installed anki-2.1.44 aqt-2.1.44

Merci pour ce super travail. 
                                                          
(*) ou [d'autres](https://repology.org/project/anki/versions)

**Comment by julien-sobczak** [comment]
Hello,

Jamais facile les soucis de dépendances :).

J'ai refait quelques tests en installant le package `apt` au lieu du package `anki`. Je n'ai pas rencontré de problème et mis à jour l'article de blog et le `README.md` du projet `anki-cli`. J'avais pin une version dans le `setup.py` car lors de mon dernier test, le package pip était plus à jour que le binaire MacOS dispo sur le site d'Anki (pb de compatibilité ascendante similaire à ton erreur). Je viens de retirer la dépendance pour laisser l'utilisateur installer lui-même la version de `aqt` qui correspond à son environnement. Ca force l'utilisateur à se poser la question afin d'éviter le genre de surprises que tu as rencontré.

Merci pour ton feedback,

**Comment by sosie-js** [comment]
Wonderfull Julien,
tu as tout compris ,c'etait dommage de barrer l'usage de ton client 
à cause juste cette contrainte aqt/anki et pas en fait de version.
