### ISSUE TITLE
A propos de tester ton client avec l'exemple cards.yaml 

### ISSUE THREAD

**Issue by sosie-js** [julien-sobczak/anki-cli#5]
1)Creer un environnemnt cloisonné
```bash
rm -r ./ankidir
#choisir imperativement english sinon ankidir 'User' traduit va foirer!
anki -l en -b ./ankidir 
```
2)Tester l'exemple avec l'import automatique

```bash
anki-cli-unofficial load cards.yaml archive.apkg --anki-dir ./ankidir/User\ 1/
```
3)Voir le résultat

```bash
anki -b ankidir
```

**Comment by julien-sobczak** [comment]
Hello,

En tentant de reproduire ton test, je suis tombé sur cette erreur:

```
$ anki-cli-unofficial load ~/Workshop/anki-cli/examples/french.yaml --media-dir ~/Workshop/anki-cli/examples  archive.apkg --anki-dir ./ankidir/User\ 1/
usage: __main__.py [-h] {load} ...
__main__.py: error: unrecognized arguments: 1/
```

Ce problème venait du script Bash appelé par le script `anki-cli-unofficial` référencé dans le `setup.py`. J'ai changé pour utiliser un script Python ce qui préserve les arguments.

Est-ce que c'est bien ce problème que tu voulais soulever à travers cette issue?

**Comment by sosie-js** [comment]
Bonjour Julien,

Ce que je voulais dire c'est que anki-dir dépend de la langue.
avec anki -b foo,  le sous répertoire utilisateur qui content la base sqlite3  "collection.anki2"
 est traduit avec la langue dans laquelle anki est lancé. 
 
 Si on  lance pas anki en anglais avec -b en et que le la locale est fr , ankidir ne pointe plus vers "foo/User 1" mais  "foo/Utilisateur 1" .

Les scripts de la [page pour les non programmeurs](https://www.juliensobczak.com/write/2020/12/26/anki-scripting-for-non-programmers.html) et [le README.md](https://github.com/julien-sobczak/anki-cli#readme)  impliquent que la locale est "en", aussi à mon avis  ce détail doit être mentionné.

**Comment by julien-sobczak** [comment]
Hello,

En effet, j'ai toujours testé depuis mon laptop avec la locale `en`. 

Je viens de retirer les références à `User 1` dans le code et documenter un exemple avec la locale `fr`. C'est fonctionnel mais pas forcément idéal. 

Merci pour ton retour,
